# Generated by IBM TransformationAdvisor
# Wed Mar 11 20:54:48 UTC 2020

FROM ibmcom/websphere-traditional:latest-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/lib 
COPY --chown=was:root application.ear /work/app
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/lib
RUN /work/configure.sh
